gcc -Wall -Werror -Wextra union.c -o union
echo "-----------------------------TEST [1]------------------------------"
echo "$>./union zpadinton "paqefwtdjetyiytjneytjoeyjnejeyj" | cat -e"
echo "-------------------------Expected result---------------------------"
echo "zpadintoqefwjy$"
echo "---------------------------Your result-----------------------------"
./union zpadinton "paqefwtdjetyiytjneytjoeyjnejeyj" | cat -e
echo "-------------------------------------------------------------------"
echo "\n"
echo "-----------------------------TEST [2]------------------------------"
echo "$>./union ddf6vewg64f gtwthgdwthdwfteewhrtag6h4ffdhsd | cat -e"
echo "-------------------------Expected result---------------------------"
echo "df6vewg4thras$"
echo "---------------------------Your result-----------------------------"
./union ddf6vewg64f gtwthgdwthdwfteewhrtag6h4ffdhsd | cat -e
echo "-------------------------------------------------------------------"
echo "\n"
echo "-----------------------------TEST [3]------------------------------"
echo "$>./union "rien" "cette phrase ne cache rien" | cat -e"
echo "-------------------------Expected result---------------------------"
echo "rienct phas$"
echo "---------------------------Your result-----------------------------"
./union "rien" "cette phrase ne cache rien" | cat -e
echo "-------------------------------------------------------------------"
echo "\n"
echo "-----------------------------TEST [4]------------------------------"
echo "$>./union | cat -e"
echo "-------------------------Expected result---------------------------"
echo "$"
echo "---------------------------Your result-----------------------------"
./union | cat -e
echo "-------------------------------------------------------------------"
echo "\n"
echo "-----------------------------TEST [5]------------------------------"
echo "$>./union "rien" | cat -e"
echo "-------------------------Expected result---------------------------"
echo "$"
echo "---------------------------Your result-----------------------------"
./union "rien" | cat -e
echo "-------------------------------------------------------------------"
rm -rf union